// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var verifier = artifacts.require('verifier');
const zkProof = require("../../zokrates/proof.json");

contract('verifier', _ => {

    describe('test verifier zokrates contract', function () {
        beforeEach(async function () {
            this.contract = await verifier.new();
        })

        it('verification with correct proof', async function () {
            let result = await this.contract.verifyTx.call(
                zkProof.proof.a,
                zkProof.proof.b,
                zkProof.proof.c,
                zkProof.inputs
            );
            assert.equal(result, true, "Incorrect proof result")
        })

        it('verification with incorrect proof', async function () {
            let result = await this.contract.verifyTx.call(
                zkProof.proof.c,
                zkProof.proof.b,
                zkProof.proof.a,
                zkProof.inputs
            );
            assert.equal(result, false,  "Incorrect proof result");
        })
    });
})